"""add_kind_to_transactions

Revision ID: add_kind_to_transactions
Revises:
Create Date: 2024-11-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_kind_to_transactions'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('kind', sa.Enum('normal', 'adjustment', name='transactionkind'), nullable=False, default='normal'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'kind')
    # ### end Alembic commands ###
